const scDict = {
  PosLib: "PosLib",
  StoremanUtil: "StoremanUtil",
  StoremanGroupProxy: "StoremanGroupProxy",
  StoremanGroupDelegate: "StoremanGroupDelegate",
  CommonTool: "CommonTool",
  MetricProxy: "MetricProxy",
  MetricDelegate: "MetricDelegate",
  MetricLib: "MetricLib",

  FakeSmg: "FakeSmg",
  FakeSkCurve: "FakeSkCurve",
  FakeBnCurve: "FakeBnCurve",
  FakePosLib: "FakePosLib",
  FakeMetric: "FakeMetric",
  FakeCommonTool: "FakeCommonTool",
  TestDeposit: "TestDeposit",
  fakeQuota: "fakeQuota",

  Secp256k1Curve: "Secp256k1Curve",
  Bn256Curve: "Bn256Curve",
  GpkLib: "GpkLib",
  GpkProxy: "GpkProxy",
  GpkDelegate: "GpkDelegate",
  Deposit: "Deposit",
  StoremanLib: "StoremanLib",
  IncentiveLib: "IncentiveLib",
  ListGroup: "ListGroup",

  ConfigProxy: "ConfigProxy",
  ConfigDelegate: "ConfigDelegate",

  TokenManagerDelegate: "TokenManagerDelegate",
  TokenManagerProxy: "TokenManagerProxy",
  QuotaDelegate: "QuotaDelegate",
  QuotaProxy: "QuotaProxy",
  OracleDelegate: "OracleDelegate",
  OracleProxy: "OracleProxy",
  SignatureVerifier: "SignatureVerifier",
  Bn128SchnorrVerifier: "Bn128SchnorrVerifier",
  Secp256k1SchnorrVerifier: "Secp256k1SchnorrVerifier",
  HTLCTxLib: "HTLCTxLib",
  HTLCDebtLib: "HTLCDebtLib",
  // HTLCBurnLib: "HTLCBurnLib",
  // HTLCMintLib: "HTLCMintLib",
  RapidityLib: "RapidityLib",
  CrossDelegate: "CrossDelegate",
  CrossProxy: "CrossProxy",
};

module.exports = scDict;
